local colors = require('tokyonight.colors')

local settings = {
    header = {
        type = 'text',
        oldfiles_directory = false,
        align = 'center',
        fold_section = false,
        title = "Header",
        margin = 2,
        content = {
--"                                                                                       ░░      ",
--"                                                   ░░░░    ░░      ░░        ░░      ░░        ",
--"                                                   ░░▒▒░░▒▒    ░░  ▒▒        ░░░░  ░░▒▒        ",
--"                                                         ▒▒▒▒  ▒▒▒▒      ▒▒▒▒  ▒▒▒▒▒▒    ▒▒▒▒  ",
--"                                                 ░░░░    ▒▒▒▒▒▒▒▒          ▒▒  ░░▒▒      ▒▒    ",
--"                                               ▒▒░░            ▒▒░░    ▒▒▒▒  ▒▒▒▒▒▒  ░░▒▒      ",
"                                               ░░▒▒▒▒▒▒    ▒▒  ▒▒▒▒▒▒  ▒▒      ▒▒▒▒▒▒▒▒        ",
"                                                   ░░▒▒▒▒▒▒      ░░▒▒▒▒▒▒▒▒      ▒▒▒▒          ",
"                                                       ▒▒▒▒▒▒▒▒░░    ▒▒▒▒    ▒▒▒▒▒▒    ▒▒▒▒    ",
"                                                 ░░▒▒▒▒        ▒▒░░    ▒▒▒▒    ▒▒▒▒▒▒▓▓        ",
"                                                             ▒▒▒▒▒▒▓▓▒▒  ▒▒▒▒  ▒▒▒▒            ",
"                                                         ░░▒▒▒▒  ░░░░▒▒▒▒▒▒▒▒░░▒▒▓▓            ",
"                                                                 ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒          ",
"    ██████╗ ███████╗███████╗██████╗ ██╗   ██╗██╗███╗   ███╗      ░░░░▒▒▒▒▒▒▒▒▒▒▒▒██▒▒▓▓        ",
"    ██╔══██╗██╔════╝██╔════╝██╔══██╗██║   ██║██║████╗ ████║        ░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░▓▓  ",
"    ██║  ██║█████╗  █████╗  ██████╔╝██║   ██║██║██╔████╔██║            ▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░  ",
"    ██║  ██║██╔══╝  ██╔══╝  ██╔══██╗╚██╗ ██╔╝██║██║╚██╔╝██║            ▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░  ",
"    ██████╔╝███████╗███████╗██║  ██║ ╚████╔╝ ██║██║ ╚═╝ ██║            ▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░    ",
"    ╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚═╝╚═╝     ╚═╝            ▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░      ",
"                                                                     ░░▓▓▓▓▒▒▒▒▒▒░░            ",
"                                                                     ▓▓▓▓▓▓▒▒▒▒▒▒              ",
"                                                                     ▓▓▓▓▓▓▒▒▒▒▒▒░░            ",
"                                                                   ░░▓▓▓▓▓▓▓▓▒▒▒▒▒▒            ",
        },
        highlight = 'Statement',
        default_color = colors.magenta,
        oldfiles_amount = 0,
    },
    body = {
        type = "text",
        highlight = "Statement",
        default_color = colors.blue2,
        fold_section = false,
        content={
            "- Coding is a mistake -",
            "",
            "(󱁐 ) para keymaps",
            "(:q) para salir",
        },
        align="center",
        title="Body",
        margin=3,
    },
    footer = {
        type = "text",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Footer",
        margin = 2,
        content = { "Version 0.3 -   - StudioCaribu" },
        highlight = "Number",
        default_color = colors.fg_dark,
        oldfiles_amount = 0,
    },
    --opciones
    options = {
        mapping_keys = false,
        cursor_column = 0.5,
        empty_lines_between_mappings = true,
        disable_statuslines = true,
        paddings = {1, 3, 3, 1},
    },
    mappings = {
        execute_command = "<CR>",
        open_file = 'o',
        open_file_split = "<c-o>",
        open_section = "<TAB>",
        open_help = "?"
    },
    colors = {
        background = colors.bg_dark,
        folded_section = colors.bg,
    },
    parts = { "header", "body", "footer" },
}

return settings
