#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config automatic_scheme    alternate
bspc config border_width         4
bspc config window_gap          15

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier     mod4
#bspc config pointer_follows_focus true
bspc config click_to_focus true 
bspc config focus_follows_pointer false
#bspc config 

#Config 144hz
bspc config pointer_motion_interval 7
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

#App Rules
bspc rule -a Alacritty state=pseudo_tiled follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Brave-browser desktop='^2'
#bspc rule -a firefox desktop='^2'
#bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Thunar state=pseudo_tiled 
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop='^3'
bspc rule -a Zathura state=pseudo_tiled center=on
bspc rule -a zoom desktop='^4' state=floating center=on follow=on border=off
bspc rule -a mpv desktop='^6' state=fullscreen follow=on node=@^6:/#biggest.local
bspc rule -a Steam desktop='^5'
bspc rule -a obs desktop='^9' state=pseudo_tiled follow=on
bspc rule -a discord desktop='^4'
bspc rule -a Nitrogen state=floating center=on
bspc rule -a 1Password state=floating center=on follow=on
bspc rule -a Protonvpn desktop='^0' state=floating center=on
bspc rule -a Transmission-gtk desktop='^0' state=pseudo_tiled
bspc rule -a Pavucontrol state=pseudo_tiled follow=on


bspc rule -a Zotero desktop='^8' state=pseudo_tiled
bspc rule -a Zotero:*:"Zotero Preferences" state=floating focus=on
bspc rule -a Zotero:*:"Quick Format Citation" state=floating focus=on sticky=on
bspc rule -a Zotero:*:"Progress" state=floating
bspc rule -a Zotero:*:"Zotero - Document Preferences" state=floating

# Border
bspc config focused_border_color        "#bb9af7"
bspc config normal_border_color         "#565f89"
bspc config active_border_color         "#bb9af7"
bspc config presel_feedback_color       "#449dab"
#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
#picom -b &
# Network Applet
nm-applet --indicator &
# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
#~/.config/bspwm/scripts/low_bat_notifier.sh

# Disable DPMS 
xset -dpms &
xset s off &
xset s noblank &


