#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
# picom &
dunst &
$HOME/.config/polybar/launch.sh &

#Screen power settings
xset dpms 300 600 900 &
xset s off &
xset s noblank &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config automatic_scheme     alternate
bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier     mod4
#para 144hz
bspc config pointer_motion_interval 7
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
#
# App Rules
#

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Brave-browser desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop='^3'
bspc rule -a Zathura state=tiled
#bspc rule -a 'zoom ' desktop='^4' state=floating center=on follow=on border=off
bspc rule -a zoom desktop='^4' state=floating center=on follow=on border=off
bspc rule -a mpv desktop='^6' state=fullscreen follow=on
bspc rule -a Steam desktop='^5'
bspc rule -a obs desktop='^9' state=tiled follow=on
bspc rule -a discord desktop='^4'
bspc rule -a Nitrogen state=floating center=on
bspc rule -a 1Password state=floating center=on follow=on

#Reglas de Zotero
bspc rule -a Zotero desktop='^8'
bspc rule -a Zotero:*:"Zotero Preferences" state=floating focus=on
bspc rule -a Zotero:*:"Quick Format Citation" state=floating focus=on sticky=on
bspc rule -a Zotero:*:"Progress" state=floating
bspc rule -a Zotero:*:"Zotero - Document Preferences" state=floating
