#!/bin/sh

awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc |
    column -t -s $'\t' |
    dmenu -l 10 -x 830 -y 400 -w 900 -fn "Iosevka-14" -dim 0.6 -sb "#7aa2f7" -p "Hotkey Help" &> /dev/null
